intents={"greeting":{"patterns":["Hello","Hi","Howdy","Greetings","Good Morning","Good afternoon",
        "Good evening","Hi there","Hey there","Whats up","Hello there","नमस्ते","प्रणाम","अभिवादन"],
        "responses":["Hello How can I assist you?","Hi there!","Hey! What can I do for you?",
                     "Howdy! What brings you here?","Greetings! How may I help you?",
                     "Good Morning! How can I be of service","Good afternoon! What do you need assistance with?",
                     "Good evening! How may I assist you?","Hey there! How can I help you?","Hi! What's on your mind",
                     "Hello there! How can I assist you there?", "नमस्ते बताइए मैं आपकी कैसे सेवा कर सकती हूँ?",
                     "प्रनाम सेवा बताइये?", "अभिवादन मैं आपकी क्या सेवा कर सकती हूँ?"]}}
Crime={"Police":{"patterns":["abduction","arson","assassination","assault","bigamy","blackmail","bombing",
                              "bribery","burglary","child abuse	","corruption","crime","cybercrime","domestic violence	",
                              "drunk driving", "fraud","hijacking","hit and run	","identity theft","kidnapping",
                              "looting","mugging","murder","pickpocketing","poaching","rape","riot","robbery",
                              "shoplifting","smuggling","speeding","terrorism","theft","trafficking","treason",
                              "trespassing","vandalism","हत्यारा","आक्रमण","धोखा देना ","अपराध","नष्ट करना",
                              "गैरकानूनी","अपहरण","मारना","लूट","तस्कर","जासूस","आतंकवादी","चोर","हिंसा","हिंसक"],
                "responses":["Dont worry! Police is on the way to help you. Their GPS location is being sent to you on your phone number!",
                             "Stay away from fire. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Try to stop it. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Get people away from that place. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Try to record the crime on your phone. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Try to record it on your phone. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Try to record the crime on your phone. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Try to record it on your phone. Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to investigate the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to stop the crime.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Dont touch the incident site or the dead body.Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "Police is coming to handle the situation.Their GPS location is being sent to you on your phone number!",
                             "पुलिस आ रही है सावधान रहे जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है","पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                             "पुलिस आ रही है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है"]}}
Medical ={"ambulance":{"patterns":["accident","burn","fire","construction","Emergency services","Medical assistance",
                                   "Healthcare services","Medical care","Urgent care","Medical aid",
                                   "Physician services","Clinical services","Hospital services","Health services",
                                   "चिकित्सा सेवाएँ","चिकित्सा सुविधाएँ","रोगी सेवाएँ","स्वास्थ्य सेवाएँ","चिकित्सा सहायता","चिकित्सा सहायक सेवाएँ",
                                   "चिकित्सकीय सेवाएँ"],
                        "responses":["Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "Ambulance is on the way. Its GPS location is being sent on your mobile number!",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है", 
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                     "रोगी वाहन आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है"]}}
fire= {"Firebrigade":{"Patterns":["Fire department","Fire service","Fire brigade","Fire rescue","Firefighters",
                                  "Fire response team","Emergency fire services","Fire suppression services",
                                  "Firefighting unit","Fire prevention and control agency","fire","smoke",
                                  "अग्निशमन सेवा","अग्निशमन विभाग","फायर ब्रिगेड सेवा ","आग","धुआँ"],
                       "responses":["Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "Fire brigade is on their way, Their GPS location is sent your mobile phone!",
                                    "अग्नि शामक दल आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                    "अग्नि शामक दल आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                    "अग्नि शामक दल आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                    "अग्नि शामक दल आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है",
                                    "अग्नि शामक दल आ रहा है जीपीएस जगह आपके मोबाइल पर भेजी जा चुकी है"]}}